### ISSUE TITLE
Sweep (slow): 新たにワークフローを作成してください

### ISSUE THREAD

**Issue by sinsky** [sinsky/go-example#16]
### Details

pull_requestで、変更が発生した量に応じてラベルをつける`pascalgn/size-label-action@v0.5.0`のフローを作成してください。
参考となる`size-label.yml`はこちらです
```yml
name: size-label
on: pull_request_target
jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

<details open>
<summary>Checklist</summary>

- [X] `.github/workflows/size-label.yml`
> • Add the following content to the file:
> ```yml
> name: size-label
> on: pull_request_target
> jobs:
>   size-label:
>     permissions:
>       contents: read
>       pull-requests: write
>     runs-on: ubuntu-latest
>     steps:
>       - name: size-label
>         uses: "pascalgn/size-label-action@v0.5.0"
>         env:
>           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
> ```

</details>
