### ISSUE TITLE
Sweep: dependency botがpull_requestを送ってきたら、自動でマージするアクションを作成してください

### ISSUE THREAD

**Issue by sinsky** [sinsky/go-example#29]
### Details

ファイルの内容は下記にしてください
```
name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

<details open>
<summary>Checklist</summary>

- [X] `.github/workflows/dependabot_auto_merge.yml`
> • Copy the content provided in the issue description into this file. The content defines a GitHub action that automatically merges pull requests made by Dependabot if the update is a patch version update for a specific dependency.

</details>
